# Generated by Django 5.0 on 2024-01-24 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('port', models.IntegerField()),
                ('protocol', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=50)),
                ('uptime', models.CharField(max_length=20)),
            ],
        ),
    ]
